name: "Build and run node-test"
on:
  push:
    paths:
      - "node/**"
      - "crates/**"
      - "pallets/*"
      - "runtime/*"
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Increase swap
        run: |
          sudo swapoff -a
          sudo dd if=/dev/zero of=/swapfile bs=1G count=8
          sudo chmod 0600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          grep Swap /proc/meminfo
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies/
      - name: Build entropy-protocol nodejs package
        run: |
          cd crates/protocol
          make build-nodejs-testing
          cd nodejs-test
          yarn
          cd ../../..
      - name: Run cargo test
        # in our circle_ci we have no_output_timeout, but equivalent does not exist in gh action i think?
        # see: https://github.com/orgs/community/discussions/125394
        run: |
          pushd node
          cargo build --all-targets --release -j $(nproc)
          cargo test --all-targets --release
          yarn --cwd ../crates/protocol/nodejs-test test
          cargo test -p entropy-tss --release --features=test_helpers -F wasm_test test_wasm
