name: "Check chainspecs"
on:
  push:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-dependencies/
      - name: check chainspecs
        run: |
          cargo run -p entropy -- build-spec --raw --chain dev > chainspec-dev-raw.json
          cargo run -p entropy -- build-spec --raw --chain integration-tests > chainspec-integration-raw.json
          cargo run -p entropy -- build-spec --raw --chain testnet > chainspec-testnet-raw.json
