---
name: "Check documentation build"
on: ["push"]

jobs:
  check-doc-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install dependencies and check licenses
        uses: ./.github/actions/install-dependencies/
      - name: Build documentation
        run: cargo doc --no-deps