name: "Check documentation build"
on:
  push:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-dependencies/
      - name: check chainspecs
        run: cargo doc --no-deps
