name: "Lint and check licenses"
on:
  push:
    paths:
      - "node/**"
      - "crates/**"
      - "pallets/*"
      - "runtime/*"
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo sed -i "/#\$nrconf{restart} = 'i';/s/.*/\$nrconf{restart} = 'a';/" /etc/needrestart/needrestart.conf
          sudo apt-get update
          sudo apt install -y libssl-dev clang libclang-dev tor protobuf-compiler
          sudo systemctl start tor
          sudo systemctl enable tor
      - name: Add rust components
        run: |
          rustup target add wasm32-unknown-unknown
          rustup component add rust-src
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Format and lint
        run: |
          curl -LsSf https://github.com/tamasfe/taplo/releases/download/0.8.0/taplo-full-linux-x86_64.gz | gunzip -N -d - > ${CARGO_HOME:-~/.cargo}/bin/taplo && chmod +x ${CARGO_HOME:-~/.cargo}/bin/taplo
          cargo fmt --check
          taplo fmt --check
          cargo clippy -- -D warnings
  check-licenses:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Check licenses with cargo deny
        run: |
          cargo install --locked cargo-deny
          cargo deny --all-features check license
