name: "Test: check runtime benchmarks"
on:
  push:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-dependencies/
      - name: check runtime-benchmarks
        run: |
          pushd node && cargo check --features=runtime-benchmarks
